from rsf.proj import *
import math


##################################################
## Velocity Model


# V_fast
v_background=3.5


# Angle between V_fast and x1 axes
angle_deg=105


# Percent anisotropy (1-V_slow/V_fast)*100
vfvs_perc_aniso=7


vf=v_background
vs=vf-((vfvs_perc_aniso/100.0)*vf)
wf=1.0/(vf*vf)
ws=1.0/(vs*vs)

#print vf
#print vs

deg2rad=math.pi/180.0
angle_rad=(angle_deg)*deg2rad
c=math.cos(angle_rad)
s=math.sin(angle_rad)


w1m=wf*c*c+ws*s*s
w12m=(wf-ws)*(s*c)
w2m=wf*s*s+ws*c*c

## Or just set the W's manually:
## w1m=1.0/4.0
## w12m=0.02
## w2m=1.0/8.41

#print w1m
#print w12m
#print w2m

Flow('w1',None,'spike n1=501 n2=101 n3=101 mag=%g d2=0.1 d3=0.1' % (w1m))
Flow('w2','w1','math output=%g'% (w2m))
Flow('w12','w1','math output=%g'% (w12m))


##################################################
## Diffractor Coordinates and Amplitudes

Flow('t',None,'spike n1=500 | noise rep=y seed=122009 type=n mean=1 range=1')
Flow('x','t','noise rep=y seed=12200 type=n mean=2.5 range=5.0')
Flow('y','t','noise rep=y seed=1220 type=n mean=2.5 range=5.0')
Flow('a','t','noise rep=y seed=122')

Flow('spikes','t x y a','cat axis=2 ${SOURCES[1:4]} | transp')

Flow('t1','t','window n1=1 | math output="1.0"')
Flow('x1','x','window n1=1 | math output="5.0"')
Flow('y1','y','window n1=1 | math output="5.0"')
Flow('a1','a','window n1=1 | math output="1.0"')
Flow('spike','t1 x1 y1 a1','cat axis=2 ${SOURCES[1:4]} | transp')


##################################################
## Diffraction Modelling

Flow('diffs','w1 w2 w12 spike',
     'diffraction freq=10 w2=${SOURCES[1]} w12=${SOURCES[2]} spikes=${SOURCES[3]}')
Plot('diffs',
     '''
     byte gainpanel=all |
     grey3 frame1=400 frame2=50 frame3=50
     label2="x\_1\^" label3="x\_2\^"
     title="a) Diffraction" pclip=99
     ''')
Result('diffs',
       '''
       byte gainpanel=all |
       grey3 frame1=400 frame2=50 frame3=50
       label2="x\_1\^" label3="x\_2\^"
       title=Diffraction pclip=99 flat=n
       ''')
End()
